### ISSUE TITLE
UTime with cross-server causes doubling

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#185]
pl._crossutimes_sum returns the player's total UTime
pl:GetUTimeTotalTime() takes the total UTime and adds on pl._crossutimes_sum
When this happens the times are doubled causing !playtime to report higher numbers than it should
Scoreboard unaffected.

Bug reported by '<color=0,150,130>Flex' (STEAM_0:0:58178275).

**Comment by Cynosphere** [comment]
Playtime report:
![](https://flexbox.xyz/ShareX/2016/07/hl2_2016-07-17_10-47-31.png)

That divided by 2 gives 2931.75, my possible server 1 hours

What scoreboard reports:
![](https://flexbox.xyz/ShareX/2016/07/hl2_2016-07-17_10-48-45.png)

2989 is what pl._crossutimes_sum/60/60 reports, which is server 2 hours added to server 1 hours, scoreboard reports 2990 because of rounding.

**Comment by Cynosphere** [comment]
Scoreboard checks if UTimeTotalTime is valid but uses pl:GetUTime() + CurTime() - pl:GetUTimeStart()

**Comment by Cynosphere** [comment]
Fixed via srvaddons 12659 by Google
