### ISSUE TITLE
Drop all flash PlayX providers to HTML5

### ISSUE THREAD

**Issue by LUModder** [Metastruct/issues#21]
The big 2
- SoundCloud: https://developers.soundcloud.com/docs/api/html5-widget
- YouTube: drop jwplayer and force everything to use html5 (will break anything disallowed for embedded playing but whatever)

Other's don't really need to be fixed because no one uses them really and files and streaming already use bass.

**Comment by PotcFdk** [comment]
Pinging @ArcticFqx

**Comment by LUModder** [comment]
Might as well add Twitch to the list of ones to fix but I don't know if they've even updated their embedded player

**Comment by Tenrys** [comment]
AFAIK awesomium isn't ready for HTML5 features.

**Comment by ArcticFqx** [comment]
When it comes to audio and video, only webm with vp8 encoded video or ogg with theora encoded video and vorbis audio is supported on gmod awesomium. This is not available on all Youtube videos. The way it is set up, it already plays most videos where embedding is disallowed on html5. Twitch uses h264 and aac, so you are stuck with flash there, same goes for any other streaming webpages.

**Comment by notcake** [comment]
ffmpeg-as-a-service? :V

**Comment by ArcticFqx** [comment]
oh god no, rip bandwidth on serverbox

**Comment by PotcFdk** [comment]
@ArcticFqx some videos (e.g. https://www.youtube.com/watch?v=2f1g6qsa05E) now fail to play inside PlayX, I think this is because the JWPlayer that we use is outdated. As it seems to be hosted on your box, can you perhaps see if you can get the .swf updated?

**update:** that's not the reason, I'll investigate this; as for this issue, I think we can close this based on [this explanation](https://github.com/Metastruct/issues/issues/21#issuecomment-153169703).

**Comment by Noiwex** [comment]
mediaplayer works without flash
