### ISSUE TITLE
restrict bhop speed in rp like it was before rp temporary removal

### ISSUE THREAD

**Issue by Vahinkolaukausosuma** [Metastruct/issues#234]

**Comment by Tenrys** [comment]
blame SpiralP for this

**Comment by ajloveslily14** [comment]
I don't see why this is an issue, everyone can bhop there so it's an even playing field

**Comment by Vahinkolaukausosuma** [comment]
The weapons in gmod are absolute shite, "most" of the hits dont register. More hits register if the target isn't going 9000 u/s

**Comment by ajloveslily14** [comment]
Sounds like an excuse for bad aim

**Comment by Vahinkolaukausosuma** [comment]
your mom have gay

**Comment by Tenrys** [comment]
I don't see how having players going around at lightspeed levels makes anything fun

**Comment by aminpeck** [comment]
I suggest that bhopping speeds be restricted to something reasonable, instead of what we've had in the past.

**Comment by ajloveslily14** [comment]
I don't really see how anything matters everyone and their mother just uses an aimbot in rp anyways

**Comment by h3xcat** [comment]
Should add CAC for RP area.

**Comment by BlueCyro** [comment]
That would be a huge waste of time, nobody actually RP's in the RP area, it's a DM area with no rules.

**Comment by Tenrys** [comment]
Someone can't detect sarcasm. In my opinion, I don't really see the point of having a DM area if everything is meant to frustrate you.

**Comment by Python1320** [comment]
People complain so there is demand. Our job is to figure out how to make it less frustrating.

My short term solution is to disable bunnyhop but maybe with some sort of powerup for temporary fastrun because the area is so big otherwise and running fast is fun crysis style. 

Also another short term solution is to add voting to players whether they play fairly or not and boot those that get enough negative votes (they can come back when the negative vote count reduces because players leave the area and such, maybe with a delay though to prevent ruining the gameplay of others to allow yourself in). Up for a concrete plan whoever figures one out first.

**Comment by ajloveslily14** [comment]
Depending on how bhopping is done could't we make it so if you're in rp you can only bhop to a certain speed? That's slower than mach 4 like normal?

**Comment by Vahinkolaukausosuma** [comment]
autojump_speed

**Comment by Tenrys** [comment]
Personally I can't be assed to deal with RP anymore, when something one meta changes it ends up breaking its flow one way or another. And I think it's unbalanced and unfun in general.

**Comment by Myaats** [comment]
I suggest that we lower the max bhop speed in rp while still making it faster that you normally can, some kind of a compromise

**Comment by Python1320** [comment]
Maybe default sandbox bunnyhop where you can only bunnyhop backwards

**Comment by AwfulRanger** [comment]
https://github.com/Facepunch/garrysmod/pull/984 not anymore you can't.

**Comment by ghost** [comment]
I would like to see this implemented as it can be quite a nuisance trying to aim at people going so fast, and it ruins the experience for players who would like to PvP instead of building or other activities.

**Comment by Vahinkolaukausosuma** [comment]
Hitreg doesnt even work beyond 2000u/s or something
woah I already said that 2 years ago but its not even that high of a value(9000) :)

**Comment by ghost** [comment]
https://i.imgur.com/axPiNRf.png

**Comment by jule14** [comment]
> Sounds like an excuse for bad aim

You can see the blood coming out when you shoot someone going damn fast and it's p much walmart godmode because none of the hits register on the server
Even slight movement can make it super hard to shoot because the acceleration is dumb fast

**Comment by jule14** [comment]
Also one interesting viewpoint could be that fast speeds are the only real way to fight against aimbotters

**Comment by cdr1996** [comment]
For me, I feel like RP area needs a bit of attention, as well as introducing more PvP or PvE options could make the server more fun. I've also had ideas for some sort of deathmatch minigames there, so I'm gonna consider all things said here and work on:

- Bunnyhop speed nerf/removal

- Some kind of rp moderation (similar to pythons idea perhaps, ability to vote out people playing unfairly in RP or add more detections for this kind of thing, repeated infarctions result in temporary RP ban)

- Overall RP overhaul, make PvP more fun by possible introduction of minigames or events in RP area, introduce possibility of powerups etc

Don't have access to a computer at the moment but happen to assign this issue to myself.

**Comment by Velcroish** [comment]
For a while now RP has just sorta sat there as an extension of build, it was always a pain in the ass back when RP had all its restrictions on pac and such due to the fact that its so closely connected to the build area. A good idea might be to have a separate PvP zone altogether accessible by televator and leave the former RP zone as is.

**Comment by cdr1996** [comment]
@Velcroish are you suggesting an existing area or an entirely newly mapped area? We would need somewhere suitable and it would probably require coding entirely new logic to account for these areas when logic exists for the RP area already. If you're suggesting an entirely new area then that would be something for the people working on the map, and again would be subject to the same thing mentioned above.

**Comment by Velcroish** [comment]
Either way, i rarely see people PVPing on meta right now; so reimplementing the RP zone restrictions would be a bit of a pointless venture. while yes, it would probably prove to be a pain in the arse to take the existing code and translate it to another area; in the long run it could prove less disruptive.

**Comment by cdr1996** [comment]
That's probably because for whatever reason, someone disabled the RP area by changing a global variable on the server. I have seen a few people try to PvP but they're either getting sent to the MTA server (because the !pvp command sends you there), or if they do go to the RP area nobody can damage each other since it's for some reason disabled.

Switching the RP area back on or adding additional logic to existing code would be simple, and for now could be a temporary solution as well as reducing the bhop speed there.

I would like to see some ideas of where else you are thinking of using as a zone for deathmatching players so feel free to shoot some ideas on here and I'll see what I can do.

**Comment by cdr1996** [comment]
Not likely to ever get worked on, closing

**Comment by Jule14** [comment]
hi jonni
