### ISSUE TITLE
Players that are actively banni are still able to get metachievements

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#256]
one's ive noticed are rehash, lag, and path of the righteous man

Bug reported by 'Some_Beach' (STEAM_0:1:55684109).

**Comment by aminpeck** [comment]
This has been around for a good few years, so it's pretty likely it isn't a bug, although it is **entirely possible** banned players could be prohibited from getting achievements in the future.

**Comment by ajloveslily14** [comment]
It used to be that if you were banni once you got blacklisted from the cheevo system but that was changed because of false bans or something

**Comment by PotcFdk** [comment]
I personally think that it's not a big deal if banned players can get achievements.
There are two ways of changing the current behavior that would make sense to me:

1. Preventing all unlocks while a player is banned.
2. Preventing only the escape-from-hell one, because a ban kinda pushes you in that direction (i.e. helps you to unlock it), and I'm generally trying to avoid these things (e.g. getting banned excludes you from the "bad example" one).

Which one do you think would be best?

**Comment by aminpeck** [comment]
From my POV, I think light restrictions on achievements for banned players are the way to go, so I'm going with option 2.

**Comment by ajloveslily14** [comment]
Yeah number 2 seems good.

**Comment by PotcFdk** [comment]
Fixed in metastruct r3622
