### ISSUE TITLE
lua editor doesnt restrict length of file names when running scripts

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#309]
![screenshot](https://i.imgur.com/RHIdNb7.png)

Bug reported by 'twentysix' (STEAM_0:0:70542806).

**Comment by PotcFdk** [comment]
@Python1320

**Comment by ajloveslily14** [comment]
Alright, I limited it to 50 characters so instead of

`[Luadev Server] <0:1:55684109|Some_Beach><ayyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy lmao>`

it'll now just be 
`[Luadev Server] <0:1:55684109|Some_Beach><ayyyyyyyyyyyyyyyyyyyyyyy...> running on Player [4][【=◈︿◈=】]
`
