### ISSUE TITLE
Subdividable cube remains in undo list after being destroyed

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#353]
Subdividable cube remains in undo list after being destroyed. Really nothing major, just a slight annoyance.

Bug reported by '<c=ff0000>Joker' (STEAM_0:1:26354828).

**Comment by ajloveslily14** [comment]
Yeah that's because the actual entity is still there, just there's no props to make it visible. A fix would be removing the entity when all of its blocks are broken, however that doesn't seem like to much of an easy thing to do because from what I see there's no real way to test how many cubes are left. I may be wrong.

**Comment by ghost** [comment]
Has anyone fixed this since

**Comment by cdr1996** [comment]
As Joker said, this is a minor annoyance. Doesn't require much attention.

**Comment by cdr1996** [comment]
Old issue and unsure if fixed or not. Reopen if required.
