### ISSUE TITLE
blacklistsound

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#412]
when i block those sounds https://i.imgur.com/1guECS3.png it blockes "abeangry" and "getting bored of space" but it shouldnt do... maybe it's a dumb bug?

Bug reported by '^7Bjoern90' (STEAM_0:1:42844056).

**Comment by PotcFdk** [comment]
Is this about the classic chatsounds or newchatsounds?

**Comment by bjoern90** [comment]
it was about newchatsounds

**Comment by cdr1996** [comment]
I think whats going on here is that the hook used in chatsound blacklist is using string.find, which means it can locate the blacklisted sound anywhere in your message. The downside I guess to this is for example, you have "bored" as one of your blacklisted sounds, so whenever its coming across the word bored its also stopping "getting bored of space" because the word bored is in it. A suggestion would be either to refine your list or maybe we need a change to the code for this to make it more accurate, but this might prove difficult and I'm not sure anyone really wants to work on this as I guess its like swatting a fly with a hammer for a minor issue.

Closed unless someone wants to reopen and tackle this issue.
