### ISSUE TITLE
Entities that are not owned by you can be teleported through the different tp dimensions

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#450]
step 1: sit on your target
step 2: press page up/down
step 3: ???
step 4: profit.

to fix, prevent teleporting between dimensions while sitting or eject before tp.

Bug reported by '<color=0,125,250>404' (STEAM_0:0:95072396).

**Comment by ghost** [comment]
Is this to do with using the sit on player command or just using alt+e (or both)?

**Comment by ghost** [comment]
Okay I just tested this and for me I don't seem to be teleporting anywhere(bug?), but when I try to teleport whilst sat on a prop this happens. https://i.imgur.com/3Tbz0IK.png

I really can't seem to reproduce this at all for myself, so if someone can reproduce this I'll investigate further otherwise this doesn't seem like a big issue to me.

EDIT: I realised I was dumb and its only teleporting stuff between the three dimensions, since they all looked the same I didn't notice any teleport. Again I don't see how this is a big issue, unless it lets you teleport other peoples entities or players. Can you confirm?

**Comment by ghost** [comment]
Couldn't replicate with players as it actually seems to be teleporting the "sit holder" entity, but can confirm it works with entities that are not owned by yourself.

**Comment by TW1STaL1CKY** [comment]
I think he was referring to the 3 identical areas above RP. Pressing PgUp and PgDn in those areas makes you jump between them like going into a different dimension.

This area doesn't exist in the latest version of the map though :v
