### ISSUE TITLE
Banned users can send SCAPs

### ISSUE THREAD

**Issue by MSReporter** [Metastruct/issues#78]
banned users can still use scaps .-. FIX IT! plus add some cmd to toggle player to send scaps bec ppl is spamming today .--.

Bug reported by '^7Bjoern90 (DEN)' (STEAM_0:1:42844056).

**Comment by Avernakis8** [comment]
Doth you mean me spammi? kek

**Comment by LUModder** [comment]
#74

**Comment by Cynosphere** [comment]
i didn't read it fully

**Comment by Cynosphere** [comment]
also #74 for the latter of "stop spamming"

**Comment by ghost** [comment]
Yeah I had the same problem yesterday.
A banned player kept sending me scaps.

**Comment by Flippylosaurus** [comment]
BANNI FOR SPAMMI

//
Deze mail is - indien anders aangegeven - vertrouwelijk en alleen 
bedoeld voor de ontvanger 
(reply@reply.github.com). 
Indien u deze mail per abuis heeft ontvangen, gelieve de mail te 
vernietigen en de verzender (hillebrand@flippylosaurus.eu) per direct te 
contacteren.

This mail is - if not mentioned otherwise - confidential and only meant 
for the recipient 
(reply@reply.github.com). 
If you have recieved this email and you are not the recipient, please 
destroy this mail and contact the originating address 
(hillebrand@flippylosaurus.eu) immediately.

**Comment by Flippylosaurus** [comment]
BANNI FOR SPAMMI

**Comment by Cynosphere** [comment]
Fixed both banned players from sending SCAPs and added SCAP blocking commands + disabling of SCAP
