### ISSUE TITLE
PAC banning

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#82]
Since PAC stealing has been on the rise lately, and that Caps' global ban system has been abandoned, some other well known people that do PAC have been discussing a way to just ban people from PAC. People might find it unfair that people are getting banned form the server just for stealing PACs. I know it won't be a perfect system as people will find ways around it if they care enough, but it's something to throw out there since there's been two cases of stealing in the last week.

> 20:16 - Travelling Merchant: give permission for meta devs to make their OWN pac ban system
> 20:17 - Travelling Merchant: Thats opt in for server owners
> 
> 20:19 - ☭ Redcyberhawk ☭: How about make a workshop addon that links with a database for server owners
> 20:19 - ☭ Redcyberhawk ☭: That links with a global PAC Ban db
> 
> 20:20 - ☭ Redcyberhawk ☭: If you're in the ban list, you can't use pac at all on any server with workshop
> 20:20 - ☭ Redcyberhawk ☭: Or github
> 20:20 - ☭ Redcyberhawk ☭: It's a simple plugin to add with PAC
> 20:20 - ☭ Redcyberhawk ☭: If steam id is this, then PAC won't work
> 20:20 - ☭ Redcyberhawk ☭: Simple enough

**Comment by PotcFdk** [comment]
I guess @CapsAdmin (hopefully (?)) wouldn't be against adding an interface to PAC that would allow for external addons to decide whether a player can use the system or not. If I understood it correctly, he removed the old system because it came with PAC and wasn't really designed to be disabled by server owners either. Then, in that case, we could build/curate a "Metastruct PAC Stealer" block list, which server owners would have to install manually (-> opt-in).
Pinging @Python1320 and @danielga for opinions.

**Comment by Noiwex** [comment]
It won't be effective and it's not even worth the hassle. Everything that is sent to client is technically stolen already by GMod client.
