### ISSUE TITLE
Add npc mapdata nodes to m3ta

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/issues#91]
http://pastebin.com/6HbreU3P

Credit to @mrpotatofactory

**Comment by Cynosphere** [comment]
It's missing angles for the sit nodes but that isn't hard

**Comment by ghost** [comment]
dead

**Comment by PotcFdk** [comment]
@TrenchFroast could you please not bump bug reports anymore?

**Comment by moonexpr** [comment]
This list isn't complete btw
I'll go ahead and upload a longer list that expires in a week

**Comment by Cynosphere** [comment]
Its a start at least for people to add on to

**Comment by moonexpr** [comment]
Temporary Map Data:
http://pastebin.com/VNnhhbbR

Handy Command:
http://pastebin.com/Bee39sHb

**Comment by ghost** [comment]
@PotcFdk woah sorry i didn't know a 1 day bug report was considered dead

**Comment by Cynosphere** [comment]
@TrenchFroast stop being stupid, it isn't a bug either

**Comment by PotcFdk** [comment]
@TrenchFroast Neither is this issue dead nor is that relevant to the fact that you shouldn't post comments when they don't add anything new. It just annoys people with unnecessary e-mails.

**Comment by ghost** [comment]
omfg why just stop
i didnt know posting a mindless message would cause such a shitstorm
now just stop because youre giving me unnecessary notifications

also to point something out the "anymore" there was completely uncalled for because i don't go ahead and post a four character comment on every single new issue do i

**Comment by moonexpr** [comment]
Posting sitting angles in a few hours.
